<nav class="navbar navbar-default">
  <div class="container-fluid">
    <h3>Pratos</h3>
  </div>
</nav>

  <?php $this->mensagem(); ?>

      <p><a class="btn btn-primary navbar-btn" href="<?php echo $this->url(array('action' => 'create')); ?>">Cadastrar novo</a></p>

  <div class="table-responsive">
    <table border="1" class="table table-bordered table-hover">
      <thead>
        <tr>
          <td class="warning"><span style="font-weight: bold">Código</td></span>
          <td class="warning"><span style="font-weight: bold">Categoria</td></span>
          <td class="warning"><span style="font-weight: bold">Titulo</td></span>
          <td class="warning"><span style="font-weight: bold">Preço</td></span>
          <td class="warning"><span style="font-weight: bold">Alterar</td></span>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->posts as $prato) { ?>
          <tr>
            <td><?php echo $prato['idprato']; ?></td>
            <td><?php echo $prato['categoria']; ?></td>
            <td><?php echo $prato['nomePrato']; ?></td>
            <td><?php echo $prato['preco']; ?></td>
            <td>
               <a class="btn btn-primary btn-xs" href="<?php echo $this->url(array('action' => 'update', 'idprato' => $prato['idprato'])); ?>">editar</a>
                <?php if ($this->podeApagar) { ?>
              <a class="btn btn-danger btn-xs" href="<?php echo $this->url(array('action' => 'delete', 'idprato' => $prato['idprato'])); ?>">apagar</a><?php } ?>
            </td>
          </tr>
          <?php } ?>
      </tbody>
    </table>
  </div>
</div>
